// - Location: src/components/editor/MarkdownEditor.tsx
import React, { useState } from 'react'
import MDEditor from '@uiw/react-md-editor'
import { Card, CardContent } from '../ui/Card'
import { Button } from '../ui/Button'
import { Input } from '../ui/Input'
import { Label } from '../ui/Label'
import { Badge } from '../ui/Badge'
import { 
  Eye, EyeOff, Save, Send, Tag, X, 
  Calendar, Clock, Image as ImageIcon, Sparkles, Wand2 
} from 'lucide-react'
import { toast } from 'sonner'

interface MarkdownEditorProps {
  initialTitle?: string
  initialContent?: string
  initialTags?: string[]
  initialCategory?: string
  isEdit?: boolean
  onSubmit: (data: any) => Promise<void>
}

const MarkdownEditor: React.FC<MarkdownEditorProps> = ({
  initialTitle = '',
  initialContent = '',
  initialTags = [],
  initialCategory = 'React',
  isEdit = false,
  onSubmit,
}) => {
  const [title, setTitle] = useState(initialTitle)
  const [content, setContent] = useState(initialContent)
  const [tags, setTags] = useState<string[]>(initialTags)
  const [tagInput, setTagInput] = useState('')
  const [category, setCategory] = useState(initialCategory)
  const [featuredImage, setFeaturedImage] = useState('')
  const [status, setStatus] = useState<'draft' | 'published'>('draft')
  const [isPreview, setIsPreview] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  
  // AI Bot States
  const [aiPrompt, setAiPrompt] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)

  const categories = ['React', 'TypeScript', 'JavaScript', 'Tailwind', 'Backend', 'DevOps', 'General']

  const handleAiGenerate = async () => {
    if (!aiPrompt.trim()) return toast.error("Please enter a prompt for the AI")
    
    setIsGenerating(true)
    try {
      // Logic for AI Bot Integration
      // Example: const response = await fetch('/api/generate', { method: 'POST', body: JSON.stringify({ prompt: aiPrompt }) })
      // For now, we simulate a delay and mock content
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      const generatedContent = `## AI Generated: ${aiPrompt}\n\nThis is a blog post about ${aiPrompt} generated by your AI Assistant. You can edit this content normally.`
      setContent(generatedContent)
      setTitle(aiPrompt)
      toast.success("Content generated successfully!")
    } catch (error) {
      toast.error("AI Generation failed")
    } finally {
      setIsGenerating(false)
    }
  }

  const handleAddTag = () => {
    if (tagInput.trim() && !tags.includes(tagInput.trim())) {
      setTags([...tags, tagInput.trim()])
      setTagInput('')
    }
  }

  const handleRemoveTag = (tagToRemove: string) => {
    setTags(tags.filter(tag => tag !== tagToRemove))
  }

  const handleSubmit = async () => {
    if (!title.trim() || !content.trim()) {
      alert('Please fill in title and content')
      return
    }

    setIsSubmitting(true)
    try {
      await onSubmit({
        title,
        content,
        excerpt: content.substring(0, 150) + '...',
        tags,
        category,
        featuredImage: featuredImage || undefined,
        status,
      })
    } catch (error) {
      console.error('Failed to save post:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-3xl font-bold">
          {isEdit ? 'Edit Post' : 'Create New Post'}
        </h1>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={() => setIsPreview(!isPreview)}>
            {isPreview ? <><EyeOff className="mr-2 h-4 w-4" /> Edit</> : <><Eye className="mr-2 h-4 w-4" /> Preview</>}
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          {/* AI Content Bot Section */}
          <Card className="border-primary/50 bg-primary/5">
            <CardContent className="p-6">
              <div className="flex items-center gap-2 mb-4">
                <Sparkles className="h-5 w-5 text-primary" />
                <h2 className="text-lg font-semibold">AI Writing Assistant</h2>
              </div>
              <div className="flex gap-2">
                <Input 
                  placeholder="What should the blog be about? (e.g. 'Future of React')" 
                  value={aiPrompt}
                  onChange={(e) => setAiPrompt(e.target.value)}
                />
                <Button onClick={handleAiGenerate} disabled={isGenerating}>
                  {isGenerating ? "Generating..." : <><Wand2 className="mr-2 h-4 w-4" /> Generate</>}
                </Button>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="title">Post Title</Label>
                  <Input
                    id="title"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    placeholder="Enter post title..."
                    className="text-lg font-semibold"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="content">Content</Label>
                  {isPreview ? (
                    <div className="prose prose-lg max-w-none p-4 border rounded-md">
                      <div dangerouslySetInnerHTML={{ __html: content }} />
                    </div>
                  ) : (
                    <div data-color-mode="light">
                      <MDEditor
                        value={content}
                        onChange={(value) => setContent(value || '')}
                        height={400}
                        preview="edit"
                      />
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Side Panel remains the same, excluding the redundant preview logic to save space */}
        <div className="space-y-6">
           <Card>
            <CardContent className="p-6">
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="category">Category</Label>
                  <select
                    id="category"
                    value={category}
                    onChange={(e) => setCategory(e.target.value)}
                    className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
                  >
                    {categories.map(cat => (
                      <option key={cat} value={cat}>{cat}</option>
                    ))}
                  </select>
                </div>

                <div className="space-y-2">
                  <Label>Tags</Label>
                  <div className="flex gap-2">
                    <Input
                      value={tagInput}
                      onChange={(e) => setTagInput(e.target.value)}
                      onKeyPress={(e) => e.key === 'Enter' && handleAddTag()}
                      placeholder="Add a tag..."
                    />
                    <Button onClick={handleAddTag} variant="outline">
                      <Tag className="h-4 w-4" />
                    </Button>
                  </div>
                  <div className="flex flex-wrap gap-2 mt-2">
                    {tags.map(tag => (
                      <Badge key={tag} variant="secondary" className="gap-1">
                        {tag}
                        <button onClick={() => handleRemoveTag(tag)} className="ml-1 hover:text-destructive">
                          <X className="h-3 w-3" />
                        </button>
                      </Badge>
                    ))}
                  </div>
                </div>

                <div className="space-y-2">
                  <Label>Status</Label>
                  <div className="flex gap-2">
                    <Button
                      type="button"
                      variant={status === 'draft' ? 'default' : 'outline'}
                      onClick={() => setStatus('draft')}
                      className="flex-1"
                    >
                      <Save className="mr-2 h-4 w-4" />
                      Draft
                    </Button>
                    <Button
                      type="button"
                      variant={status === 'published' ? 'default' : 'outline'}
                      onClick={() => setStatus('published')}
                      className="flex-1"
                    >
                      <Send className="mr-2 h-4 w-4" />
                      Publish
                    </Button>
                  </div>
                </div>

                <Button
                  onClick={handleSubmit}
                  disabled={isSubmitting}
                  className="w-full"
                >
                  {isSubmitting ? 'Saving...' : isEdit ? 'Update Post' : 'Create Post'}
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

export default MarkdownEditor