import React, { useState } from 'react'
import MDEditor from '@uiw/react-md-editor'
import { Card, CardContent, CardHeader, CardTitle } from '../ui/Card'
import { Button } from '../ui/Button'
import { Input } from '../ui/Input'
import { Label } from '../ui/Label'
import { Badge } from '../ui/Badge'
import { 
  Eye, EyeOff, Save, Send, Tag, X, 
  Image as ImageIcon, Sparkles, Wand2, Layout, 
  ArrowLeft, UploadCloud
} from 'lucide-react'
import { toast } from 'sonner'
import { useNavigate } from 'react-router-dom'

interface MarkdownEditorProps {
  initialTitle?: string
  initialContent?: string
  initialTags?: string[]
  initialCategory?: string
  isEdit?: boolean
  onSubmit: (data: any) => Promise<void>
}

const MarkdownEditor: React.FC<MarkdownEditorProps> = ({
  initialTitle = '',
  initialContent = '',
  initialTags = [],
  initialCategory = 'React',
  isEdit = false,
  onSubmit,
}) => {
  const navigate = useNavigate()
  const [title, setTitle] = useState(initialTitle)
  const [content, setContent] = useState(initialContent)
  const [tags, setTags] = useState<string[]>(initialTags)
  const [tagInput, setTagInput] = useState('')
  const [category, setCategory] = useState(initialCategory)
  const [featuredImage, setFeaturedImage] = useState('')
  const [status, setStatus] = useState<'draft' | 'published'>('draft')
  const [isPreview, setIsPreview] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  
  // AI Bot States
  const [aiPrompt, setAiPrompt] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [showAiPanel, setShowAiPanel] = useState(true)

  const categories = ['React', 'TypeScript', 'JavaScript', 'Tailwind', 'Backend', 'DevOps', 'General', 'Lifestyle']

  const handleAiGenerate = async () => {
    if (!aiPrompt.trim()) return toast.error("Please enter a prompt for the AI")
    
    setIsGenerating(true)
    try {
      await new Promise(resolve => setTimeout(resolve, 1500)) // Simulation
      
      const generatedContent = `## ${aiPrompt}\n\nHere is a draft about **${aiPrompt}** generated by your AI Assistant.\n\n* Start by explaining the core concept...\n* Add code examples...\n* Conclude with thoughts...`
      
      if (!title) setTitle(aiPrompt)
      setContent(prev => prev ? `${prev}\n\n${generatedContent}` : generatedContent)
      toast.success("AI Content generated!")
    } catch (error) {
      toast.error("AI Generation failed")
    } finally {
      setIsGenerating(false)
    }
  }

  const handleAddTag = () => {
    if (tagInput.trim() && !tags.includes(tagInput.trim())) {
      setTags([...tags, tagInput.trim()])
      setTagInput('')
    }
  }

  const handleRemoveTag = (tagToRemove: string) => {
    setTags(tags.filter(tag => tag !== tagToRemove))
  }

  const handleSubmit = async () => {
    if (!title.trim() || !content.trim()) {
      toast.error('Please add a title and some content')
      return
    }

    setIsSubmitting(true)
    try {
      await onSubmit({
        title,
        content,
        excerpt: content.substring(0, 150).replace(/[#*`]/g, '') + '...',
        tags,
        category,
        featuredImage: featuredImage || undefined,
        status,
      })
    } catch (error) {
      console.error('Failed to save post:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="min-h-screen bg-background pb-20">
      {/* Top Navigation Bar */}
      <div className="sticky top-0 z-40 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container max-w-7xl mx-auto flex h-16 items-center justify-between px-4">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <div className="hidden sm:block">
               <h1 className="text-lg font-semibold">{isEdit ? 'Edit Post' : 'New Post'}</h1>
               <p className="text-xs text-muted-foreground">{status === 'draft' ? 'Unsaved changes' : 'Ready to publish'}</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Button variant="ghost" size="sm" onClick={() => setIsPreview(!isPreview)}>
              {isPreview ? <><Layout className="mr-2 h-4 w-4" /> Edit</> : <><Eye className="mr-2 h-4 w-4" /> Preview</>}
            </Button>
            <div className="h-6 w-px bg-border mx-2" />
            <Button 
              variant="outline" 
              onClick={() => { setStatus('draft'); handleSubmit(); }}
              disabled={isSubmitting}
            >
              <Save className="mr-2 h-4 w-4" /> Save Draft
            </Button>
            <Button 
              onClick={() => { setStatus('published'); handleSubmit(); }}
              disabled={isSubmitting}
              className="bg-primary hover:bg-primary/90"
            >
              {isSubmitting ? 'Publishing...' : <><Send className="mr-2 h-4 w-4" /> Publish</>}
            </Button>
          </div>
        </div>
      </div>

      <div className="container max-w-7xl mx-auto px-4 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Main Editor Area (Left/Center) */}
          <div className="lg:col-span-8 space-y-6">
            {/* Title Input - Large & Clean */}
            <div className="space-y-4">
               <Input
                 value={title}
                 onChange={(e) => setTitle(e.target.value)}
                 placeholder="Post Title"
                 className="text-4xl font-bold border-none px-0 shadow-none focus-visible:ring-0 placeholder:text-muted-foreground/40 h-auto py-2"
               />
               {featuredImage && (
                 <div className="relative aspect-video w-full overflow-hidden rounded-xl border bg-muted/50">
                   <img src={featuredImage} alt="Cover" className="h-full w-full object-cover" />
                   <Button 
                     size="icon" 
                     variant="destructive" 
                     className="absolute top-2 right-2 h-8 w-8"
                     onClick={() => setFeaturedImage('')}
                   >
                     <X className="h-4 w-4" />
                   </Button>
                 </div>
               )}
            </div>

            {/* Editor */}
            <Card className="border-none shadow-none ring-1 ring-border sm:rounded-xl overflow-hidden">
              {isPreview ? (
                // CORRECTED: Using MDEditor.Markdown component instead of helper function
                <div className="prose prose-lg dark:prose-invert max-w-none p-8 min-h-[500px]" data-color-mode="light">
                  <MDEditor.Markdown 
                    source={content} 
                    style={{ backgroundColor: 'transparent', minHeight: '500px' }} 
                  />
                </div>
              ) : (
                <div data-color-mode="light" className="min-h-[600px]">
                  <MDEditor
                    value={content}
                    onChange={(val) => setContent(val || '')}
                    height={600}
                    preview="edit"
                    className="!border-none"
                    visibleDragbar={false}
                    textareaProps={{
                      placeholder: "Write your story here..."
                    }}
                  />
                </div>
              )}
            </Card>
          </div>

          {/* Sidebar Settings (Right) */}
          <div className="lg:col-span-4 space-y-6">
            
            {/* AI Assistant Card */}
            <Card className="bg-gradient-to-br from-primary/5 via-primary/10 to-transparent border-primary/20 shadow-sm">
              <CardHeader className="p-4 pb-2">
                <CardTitle className="text-sm font-medium flex items-center justify-between">
                  <span className="flex items-center gap-2 text-primary">
                    <Sparkles className="h-4 w-4" /> AI Assistant
                  </span>
                  <Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setShowAiPanel(!showAiPanel)}>
                    {showAiPanel ? <X className="h-3 w-3" /> : <Wand2 className="h-3 w-3" />}
                  </Button>
                </CardTitle>
              </CardHeader>
              {showAiPanel && (
                <CardContent className="p-4 pt-0 space-y-3">
                  <p className="text-xs text-muted-foreground">Ask AI to generate an outline, intro, or entire section.</p>
                  <div className="flex gap-2">
                    <Input 
                      placeholder="Topic (e.g. React Hooks)" 
                      value={aiPrompt}
                      className="bg-background/50 h-9 text-sm"
                      onChange={(e) => setAiPrompt(e.target.value)}
                    />
                    <Button size="sm" onClick={handleAiGenerate} disabled={isGenerating}>
                      {isGenerating ? <div className="animate-spin rounded-full h-3 w-3 border-2 border-current border-t-transparent" /> : <Wand2 className="h-3 w-3" />}
                    </Button>
                  </div>
                </CardContent>
              )}
            </Card>

            {/* Publishing Settings */}
            <div className="sticky top-24 space-y-6">
              <Card>
                <CardHeader className="p-4 pb-2">
                  <CardTitle className="text-sm font-medium">Post Settings</CardTitle>
                </CardHeader>
                <CardContent className="p-4 space-y-4">
                  {/* Category */}
                  <div className="space-y-2">
                    <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Category</Label>
                    <select
                      value={category}
                      onChange={(e) => setCategory(e.target.value)}
                      className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring"
                    >
                      {categories.map(cat => <option key={cat} value={cat}>{cat}</option>)}
                    </select>
                  </div>

                  {/* Featured Image */}
                  <div className="space-y-2">
                    <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Cover Image URL</Label>
                    <div className="flex gap-2">
                      <Input
                        value={featuredImage}
                        onChange={(e) => setFeaturedImage(e.target.value)}
                        placeholder="https://..."
                        className="text-sm"
                      />
                      <Button size="icon" variant="outline" title="Preview" disabled={!featuredImage}>
                        <ImageIcon className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>

                  {/* Tags */}
                  <div className="space-y-2">
                    <Label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Tags</Label>
                    <div className="flex flex-wrap gap-2 mb-2">
                      {tags.map(tag => (
                        <Badge key={tag} variant="secondary" className="hover:bg-destructive/10 hover:text-destructive cursor-pointer transition-colors" onClick={() => handleRemoveTag(tag)}>
                          {tag} <X className="ml-1 h-2 w-2" />
                        </Badge>
                      ))}
                    </div>
                    <div className="relative">
                      <Tag className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                      <Input
                        value={tagInput}
                        onChange={(e) => setTagInput(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && handleAddTag()}
                        placeholder="Add tags..."
                        className="pl-9"
                      />
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Tips Card */}
              <Card className="bg-muted/30 border-dashed">
                <CardContent className="p-4">
                  <h4 className="font-medium text-sm mb-2 flex items-center gap-2">
                    <UploadCloud className="h-4 w-4" /> Publishing Tips
                  </h4>
                  <ul className="text-xs text-muted-foreground list-disc pl-4 space-y-1">
                    <li>Use clear, concise headings.</li>
                    <li>Add code blocks for technical examples.</li>
                    <li>Preview your post before publishing.</li>
                  </ul>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default MarkdownEditor