import React, { useState } from 'react'
import MDEditor from '@uiw/react-md-editor'
import { Card, CardContent, CardHeader, CardTitle } from '../ui/Card'
import { Button } from '../ui/Button'
import { Input } from '../ui/Input'
import { Label } from '../ui/Label'
import { Badge } from '../ui/Badge'
import { Textarea } from '../ui/Textarea'
import { 
  Eye, Save, Send, Tag, X, Image as ImageIcon, 
  Sparkles, Wand2, Layout, PenTool, ArrowLeft 
} from 'lucide-react'
import { toast } from 'sonner'
import { useNavigate } from 'react-router-dom'

interface MarkdownEditorProps {
  initialTitle?: string
  initialContent?: string
  initialTags?: string[]
  initialCategory?: string
  isEdit?: boolean
  onSubmit: (data: any) => Promise<void>
}

const MarkdownEditor: React.FC<MarkdownEditorProps> = ({
  initialTitle = '',
  initialContent = '',
  initialTags = [],
  initialCategory = 'Technology',
  isEdit = false,
  onSubmit,
}) => {
  const navigate = useNavigate()
  const [title, setTitle] = useState(initialTitle)
  const [content, setContent] = useState(initialContent)
  const [tags, setTags] = useState<string[]>(initialTags)
  const [tagInput, setTagInput] = useState('')
  const [category, setCategory] = useState(initialCategory)
  const [featuredImage, setFeaturedImage] = useState('')
  const [status, setStatus] = useState<'draft' | 'published'>('draft')
  const [activeTab, setActiveTab] = useState<'write' | 'preview'>('write')
  const [isSubmitting, setIsSubmitting] = useState(false)
  
  // AI Bot States
  const [aiPrompt, setAiPrompt] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)

  const categories = ['Technology', 'Lifestyle', 'Programming', 'React', 'Design', 'Career']

  const handleAiGenerate = async () => {
    if (!aiPrompt.trim()) return toast.error("Please enter a prompt for the AI")
    
    setIsGenerating(true)
    try {
      await new Promise(resolve => setTimeout(resolve, 1500))
      const generatedContent = `## ${aiPrompt}\n\nHere is a draft about **${aiPrompt}** generated by your AI Assistant.\n\n* Point 1\n* Point 2\n\nStart writing your amazing story here...`
      setContent(generatedContent)
      if (!title) setTitle(aiPrompt)
      toast.success("AI draft generated!")
    } catch (error) {
      toast.error("AI Generation failed")
    } finally {
      setIsGenerating(false)
    }
  }

  const handleAddTag = () => {
    if (tagInput.trim() && !tags.includes(tagInput.trim())) {
      setTags([...tags, tagInput.trim()])
      setTagInput('')
    }
  }

  const handleRemoveTag = (tagToRemove: string) => {
    setTags(tags.filter(tag => tag !== tagToRemove))
  }

  const handleSubmit = async (targetStatus: 'draft' | 'published') => {
    if (!title.trim()) {
      toast.error('Please enter a post title')
      return
    }
    if (!content.trim()) {
      toast.error('Post content cannot be empty')
      return
    }

    setIsSubmitting(true)
    try {
      await onSubmit({
        title,
        content,
        excerpt: content.substring(0, 150) + '...',
        tags,
        category,
        featuredImage: featuredImage || `https://source.unsplash.com/random/800x600/?${category}`,
        status: targetStatus,
      })
    } catch (error) {
      console.error('Failed to save post:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Top Navigation Bar */}
      <div className="border-b bg-card sticky top-0 z-50">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="sm" onClick={() => navigate(-1)}>
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back
            </Button>
            <div className="h-6 w-px bg-border mx-2" />
            <span className="font-semibold text-lg">{isEdit ? 'Edit Post' : 'New Story'}</span>
            <Badge variant="secondary" className="hidden md:inline-flex">
              {status === 'published' ? 'Published' : 'Draft'}
            </Badge>
          </div>

          <div className="flex items-center gap-2">
             <div className="bg-muted p-1 rounded-lg flex items-center mr-4">
              <button
                onClick={() => setActiveTab('write')}
                className={`px-3 py-1.5 text-sm font-medium rounded-md transition-all ${
                  activeTab === 'write' ? 'bg-background shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                <PenTool className="h-4 w-4 inline mr-2" />
                Write
              </button>
              <button
                onClick={() => setActiveTab('preview')}
                className={`px-3 py-1.5 text-sm font-medium rounded-md transition-all ${
                  activeTab === 'preview' ? 'bg-background shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                <Eye className="h-4 w-4 inline mr-2" />
                Preview
              </button>
            </div>

            <Button 
              variant="outline" 
              onClick={() => handleSubmit('draft')}
              disabled={isSubmitting}
            >
              <Save className="h-4 w-4 mr-2" />
              Save Draft
            </Button>
            <Button 
              onClick={() => handleSubmit('published')}
              disabled={isSubmitting}
            >
              <Send className="h-4 w-4 mr-2" />
              Publish
            </Button>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Main Editor Area */}
          <div className="lg:col-span-8 space-y-6">
            
            {/* Title Section */}
            <div className="space-y-4">
              {featuredImage && activeTab === 'write' && (
                <div className="relative w-full h-64 rounded-xl overflow-hidden group">
                   <img src={featuredImage} alt="Cover" className="w-full h-full object-cover" />
                   <button 
                    onClick={() => setFeaturedImage('')}
                    className="absolute top-4 right-4 bg-black/50 hover:bg-black/70 text-white p-2 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                   >
                     <X className="h-4 w-4" />
                   </button>
                </div>
              )}
              
              <Input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Article Title..."
                className="text-4xl font-bold border-none px-0 h-auto focus-visible:ring-0 placeholder:text-muted-foreground/50 bg-transparent"
              />
            </div>

            {/* AI Assistant Banner */}
            {activeTab === 'write' && (
              <Card className="bg-primary/5 border-primary/20">
                <CardContent className="p-4 flex gap-3 items-center">
                  <Sparkles className="h-5 w-5 text-primary shrink-0" />
                  <Input 
                    placeholder="Ask AI to help write..." 
                    value={aiPrompt}
                    onChange={(e) => setAiPrompt(e.target.value)}
                    className="border-primary/20 bg-background/50"
                  />
                  <Button size="sm" onClick={handleAiGenerate} disabled={isGenerating}>
                    {isGenerating ? <Wand2 className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />}
                  </Button>
                </CardContent>
              </Card>
            )}

            {/* Editor / Preview Switch */}
            <div className="min-h-[500px]">
              {activeTab === 'write' ? (
                <div data-color-mode="light" className="markdown-editor-wrapper">
                  <MDEditor
                    value={content}
                    onChange={(value) => setContent(value || '')}
                    height={600}
                    preview="edit"
                    visibleDragbar={false}
                    className="!border-none !shadow-none bg-background"
                    textareaProps={{
                      placeholder: "Tell your story...",
                    }}
                  />
                </div>
              ) : (
                <Card>
                  <CardContent className="prose prose-lg dark:prose-invert max-w-none p-8">
                    <h1>{title}</h1>
                    {featuredImage && <img src={featuredImage} alt="Cover" className="w-full rounded-lg my-6" />}
                    <div dangerouslySetInnerHTML={{ __html: MDEditor.markdownToHtml(content) }} />
                  </CardContent>
                </Card>
              )}
            </div>
          </div>

          {/* Sidebar Settings */}
          <div className="lg:col-span-4 space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Publishing Details</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                
                {/* Cover Image Input */}
                <div className="space-y-2">
                  <Label>Cover Image</Label>
                  <div className="flex gap-2">
                    <Input 
                      placeholder="https://..." 
                      value={featuredImage}
                      onChange={(e) => setFeaturedImage(e.target.value)}
                    />
                    <Button variant="outline" size="icon">
                      <ImageIcon className="h-4 w-4" />
                    </Button>
                  </div>
                  <p className="text-xs text-muted-foreground">Paste an image URL for your cover.</p>
                </div>

                {/* Category Selection */}
                <div className="space-y-2">
                  <Label>Category</Label>
                  <div className="grid grid-cols-2 gap-2">
                    {categories.map(cat => (
                      <div 
                        key={cat}
                        onClick={() => setCategory(cat)}
                        className={`cursor-pointer border rounded-md p-2 text-center text-sm transition-all ${
                          category === cat 
                            ? 'bg-primary text-primary-foreground border-primary' 
                            : 'hover:bg-muted'
                        }`}
                      >
                        {cat}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Tags Input */}
                <div className="space-y-2">
                  <Label>Tags</Label>
                  <div className="flex gap-2">
                    <Input
                      value={tagInput}
                      onChange={(e) => setTagInput(e.target.value)}
                      onKeyPress={(e) => e.key === 'Enter' && handleAddTag()}
                      placeholder="Add tags..."
                    />
                    <Button onClick={handleAddTag} size="sm" variant="secondary">
                      <Tag className="h-4 w-4" />
                    </Button>
                  </div>
                  <div className="flex flex-wrap gap-2 pt-2">
                    {tags.map(tag => (
                      <Badge key={tag} variant="secondary" className="pl-2 pr-1 py-1">
                        {tag}
                        <button onClick={() => handleRemoveTag(tag)} className="ml-1 hover:text-destructive">
                          <X className="h-3 w-3" />
                        </button>
                      </Badge>
                    ))}
                  </div>
                </div>

              </CardContent>
            </Card>
            
            {/* Helper Card */}
            <Card className="bg-muted/50 border-none shadow-none">
              <CardContent className="p-4 space-y-2">
                <h4 className="font-semibold flex items-center gap-2">
                  <Layout className="h-4 w-4" /> Writing Tips
                </h4>
                <ul className="text-sm text-muted-foreground space-y-1 list-disc pl-4">
                  <li>Use # for headings</li>
                  <li>Use **bold** for emphasis</li>
                  <li>Use &gt; for blockquotes</li>
                  <li>Add a cover image for better visibility</li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}

export default MarkdownEditor