// src/api/aiService.ts
export const aiService = {
  generateContent: async (prompt: string) => {
    // Replace this with your actual API call
    // const response = await axios.post('/api/ai/generate', { prompt });
    // return response.data;
    
    await new Promise(resolve => setTimeout(resolve, 2000));
    return {
      title: `${prompt.charAt(0).toUpperCase() + prompt.slice(1)}: A Comprehensive Guide`,
      content: `## Introduction to ${prompt}\n\nThis content was generated by your AI Assistant based on the prompt: "${prompt}".\n\n### Key Benefits\n- Efficient development cycles\n- Consistent content quality\n- Automated SEO optimization\n\n### Conclusion\nStart building your vision today.`,
      tags: [prompt.toLowerCase(), 'ai-generated', 'tech'],
      category: 'General'
    };
  }
};